project_name: dalfox
version: 2
before:
  hooks:
  - go mod download

builds:
  -
    main: .
    binary: dalfox
    goos:
      - windows
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 6
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: 386
      - goos: windows
        goarch: arm

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

changelog:
  sort: desc
  filters:
    exclude:
    - '^MERGE'
    - "{{ .Tag }}"

release:
  github:
    owner: hahwul
    name: dalfox

brews:
  -
    name: dalfox
    repository:
      owner: hahwul
      name: homebrew-dalfox
    url_template: "https://github.com/hahwul/dalfox/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: hahwul
      email: hahwul@gmail.com
    directory: Formula
    homepage: "https://dalfox.hahwul.com"
    description: Powerful open-source XSS scanner and utility focused on automation.
    test: |
      system "#{bin}/dalfox version"
    install: |
      bin.install "dalfox"
snapcrafts:
  -
    name: dalfox
    publish: true
    summary: Powerful open-source XSS scanner and utility focused on automation.
    description: DalFox is a powerful open-source tool that focuses on automation, making it ideal for quickly scanning for XSS flaws and analyzing parameters. Its advanced testing engine and niche features are designed to streamline the process of detecting and verifying vulnerabilities.
    grade: stable
    confinement: strict
    license: MIT

    apps:
      dalfox:
        plugs: ["home","network","network-bind"]
