name: csprecon
summary: Discover new target domains using Content Security Policy
description: |
      Take as input target URLs and probe them to retrieve their CSP (either from Head or Header) 
      and get new target domains.
version: 0.4.0
grade: stable
base: core20

confinement: strict

apps:
  csprecon:
    command: bin/csprecon
    plugs:
      - home
      - network

parts:
  csprecon:
    plugin: go
    source-type: git
    source: https://github.com/edoardottt/csprecon
